/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor. */
package swingszamologep;

import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import static javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW;
import javax.swing.KeyStroke;

/**
 *
 * @author Matko
 */
public class Foablak extends javax.swing.JFrame {

    String muvelet;

    public Foablak() {
        initComponents();
        rootPane.getInputMap(WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("0"), "nulla");
        rootPane.getInputMap(WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("1"), "egy");
        rootPane.getInputMap(WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("2"), "ketto");
        rootPane.getInputMap(WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("3"), "harom");
        rootPane.getInputMap(WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("4"), "negy");
        rootPane.getInputMap(WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("5"), "ot");
        rootPane.getInputMap(WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("6"), "hat");
        rootPane.getInputMap(WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("7"), "het");
        rootPane.getInputMap(WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("8"), "nyolc");
        rootPane.getInputMap(WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("9"), "kilenc");

        rootPane.getActionMap().put("nulla", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnNulla.doClick();
            }
        });
        rootPane.getActionMap().put("egy", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnEgy.doClick();
            }
        });
        rootPane.getActionMap().put("ketto", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnKetto.doClick();
            }
        });
        rootPane.getActionMap().put("harom", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnHarom.doClick();
            }
        });
        rootPane.getActionMap().put("negy", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnNegy.doClick();
            }
        });
        rootPane.getActionMap().put("ot", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnOt.doClick();
            }
        });
        rootPane.getActionMap().put("hat", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnHat.doClick();
            }
        });
        rootPane.getActionMap().put("het", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnHet.doClick();
            }
        });
        rootPane.getActionMap().put("nyolc", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnNyolc.doClick();
            }
        });
        rootPane.getActionMap().put("kilenc", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnKilenc.doClick();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfEredmeny = new javax.swing.JTextField();
        btnNyolc = new javax.swing.JButton();
        btnKilenc = new javax.swing.JButton();
        btnHet = new javax.swing.JButton();
        btnHat = new javax.swing.JButton();
        btnOt = new javax.swing.JButton();
        btnNegy = new javax.swing.JButton();
        btnEgy = new javax.swing.JButton();
        btnKetto = new javax.swing.JButton();
        btnHarom = new javax.swing.JButton();
        btnOsszeadas = new javax.swing.JButton();
        btnSzorzas = new javax.swing.JButton();
        btnKivonas = new javax.swing.JButton();
        btnOsztas = new javax.swing.JButton();
        tfKicsi = new javax.swing.JTextField();
        btnDel = new javax.swing.JButton();
        btnEgyenlo = new javax.swing.JButton();
        btnNulla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tfEredmeny.setFont(new java.awt.Font("Times New Roman", 1, 110)); // NOI18N
        tfEredmeny.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfEredmeny.setText("0");
        tfEredmeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEredmenyActionPerformed(evt);
            }
        });

        btnNyolc.setBackground(new java.awt.Color(102, 102, 102));
        btnNyolc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNyolc.setText("8");
        btnNyolc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyolcActionPerformed(evt);
            }
        });

        btnKilenc.setBackground(new java.awt.Color(102, 102, 102));
        btnKilenc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnKilenc.setText("9");
        btnKilenc.setPreferredSize(new java.awt.Dimension(90, 90));
        btnKilenc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKilencActionPerformed(evt);
            }
        });

        btnHet.setBackground(new java.awt.Color(102, 102, 102));
        btnHet.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHet.setText("7");
        btnHet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHetActionPerformed(evt);
            }
        });

        btnHat.setBackground(new java.awt.Color(102, 102, 102));
        btnHat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHat.setText("6");
        btnHat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHatActionPerformed(evt);
            }
        });

        btnOt.setBackground(new java.awt.Color(102, 102, 102));
        btnOt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOt.setText("5");
        btnOt.setPreferredSize(new java.awt.Dimension(90, 90));
        btnOt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtActionPerformed(evt);
            }
        });

        btnNegy.setBackground(new java.awt.Color(102, 102, 102));
        btnNegy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNegy.setText("4");
        btnNegy.setPreferredSize(new java.awt.Dimension(90, 90));
        btnNegy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegyActionPerformed(evt);
            }
        });

        btnEgy.setBackground(new java.awt.Color(102, 102, 102));
        btnEgy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEgy.setText("1");
        btnEgy.setPreferredSize(new java.awt.Dimension(90, 90));
        btnEgy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEgyActionPerformed(evt);
            }
        });

        btnKetto.setBackground(new java.awt.Color(102, 102, 102));
        btnKetto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnKetto.setText("2");
        btnKetto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKettoActionPerformed(evt);
            }
        });

        btnHarom.setBackground(new java.awt.Color(102, 102, 102));
        btnHarom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHarom.setText("3");
        btnHarom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHaromActionPerformed(evt);
            }
        });

        btnOsszeadas.setBackground(new java.awt.Color(204, 204, 204));
        btnOsszeadas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOsszeadas.setText("+");
        btnOsszeadas.setPreferredSize(new java.awt.Dimension(90, 90));
        btnOsszeadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsszeadasActionPerformed(evt);
            }
        });

        btnSzorzas.setBackground(new java.awt.Color(204, 204, 204));
        btnSzorzas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSzorzas.setText("*");
        btnSzorzas.setPreferredSize(new java.awt.Dimension(90, 90));
        btnSzorzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSzorzasActionPerformed(evt);
            }
        });

        btnKivonas.setBackground(new java.awt.Color(204, 204, 204));
        btnKivonas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnKivonas.setText("-");
        btnKivonas.setPreferredSize(new java.awt.Dimension(90, 90));
        btnKivonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKivonasActionPerformed(evt);
            }
        });

        btnOsztas.setBackground(new java.awt.Color(204, 204, 204));
        btnOsztas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOsztas.setText("/");
        btnOsztas.setPreferredSize(new java.awt.Dimension(90, 90));
        btnOsztas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsztasActionPerformed(evt);
            }
        });

        tfKicsi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfKicsi.setText("0");
        tfKicsi.setRequestFocusEnabled(false);
        tfKicsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKicsiActionPerformed(evt);
            }
        });

        btnDel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDel.setText("DEL");
        btnDel.setPreferredSize(new java.awt.Dimension(90, 90));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnEgyenlo.setBackground(new java.awt.Color(204, 204, 204));
        btnEgyenlo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEgyenlo.setText("=");
        btnEgyenlo.setPreferredSize(new java.awt.Dimension(90, 90));
        btnEgyenlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEgyenloActionPerformed(evt);
            }
        });

        btnNulla.setBackground(new java.awt.Color(102, 102, 102));
        btnNulla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNulla.setText("0");
        btnNulla.setPreferredSize(new java.awt.Dimension(90, 90));
        btnNulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNullaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnHat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnOt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnNegy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSzorzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnHet)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnNyolc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnKilenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnOsztas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnHarom)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnKetto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEgy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnKivonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnNulla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEgyenlo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnOsszeadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfEredmeny)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(tfKicsi, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(25, 25, 25)))
                    .addContainerGap()))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHet, btnKilenc, btnNyolc});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHat, btnNegy, btnOt});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEgy, btnHarom, btnKetto});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(tfKicsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(61, 61, 61)
                    .addComponent(tfEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHet)
                        .addComponent(btnNyolc)
                        .addComponent(btnKilenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOsztas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHat)
                        .addComponent(btnOt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNegy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSzorzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHarom)
                        .addComponent(btnKetto)
                        .addComponent(btnEgy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnKivonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEgyenlo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOsszeadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNulla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHet, btnKilenc, btnNyolc});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHat, btnNegy, btnOt});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEgy, btnHarom, btnKetto});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNyolcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyolcActionPerformed
        if (tfEredmeny.getText().equals("0")) {
            tfEredmeny.setText("8");
        } else {
            tfEredmeny.setText(tfEredmeny.getText() + "8");
        }
    }//GEN-LAST:event_btnNyolcActionPerformed

    private void btnKivonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKivonasActionPerformed
//        int abla = Integer.parseInt(tfKicsi.getText())-Integer.parseInt(tfEredmeny.getText()); 
        tfKicsi.setText(tfEredmeny.getText());
        tfEredmeny.setText("0");
        muvelet = "-";
    }//GEN-LAST:event_btnKivonasActionPerformed

    private void tfEredmenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEredmenyActionPerformed

    }//GEN-LAST:event_tfEredmenyActionPerformed

    private void btnNullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNullaActionPerformed
        if (tfEredmeny.getText().equals("0")) {
            tfEredmeny.setText("0");
        } else {
            tfEredmeny.setText(tfEredmeny.getText() + "0");
        }
    }//GEN-LAST:event_btnNullaActionPerformed

    private void btnEgyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgyActionPerformed
        if (tfEredmeny.getText().equals("0")) {
            tfEredmeny.setText("1");
        } else {
            tfEredmeny.setText(tfEredmeny.getText() + "1");
        }

    }//GEN-LAST:event_btnEgyActionPerformed

    private void btnKettoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKettoActionPerformed
        if (tfEredmeny.getText().equals("0")) {
            tfEredmeny.setText("2");
        } else {
            tfEredmeny.setText(tfEredmeny.getText() + "2");
        }
    }//GEN-LAST:event_btnKettoActionPerformed

    private void btnHaromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHaromActionPerformed
        if (tfEredmeny.getText().equals("0")) {
            tfEredmeny.setText("3");
        } else {
            tfEredmeny.setText(tfEredmeny.getText() + "3");
        }
    }//GEN-LAST:event_btnHaromActionPerformed

    private void btnNegyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegyActionPerformed
        if (tfEredmeny.getText().equals("0")) {
            tfEredmeny.setText("4");
        } else {
            tfEredmeny.setText(tfEredmeny.getText() + "4");
        }
    }//GEN-LAST:event_btnNegyActionPerformed

    private void btnOtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtActionPerformed
        if (tfEredmeny.getText().equals("0")) {
            tfEredmeny.setText("5");
        } else {
            tfEredmeny.setText(tfEredmeny.getText() + "5");
        }
    }//GEN-LAST:event_btnOtActionPerformed

    private void btnHatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHatActionPerformed
        if (tfEredmeny.getText().equals("0")) {
            tfEredmeny.setText("6");
        } else {
            tfEredmeny.setText(tfEredmeny.getText() + "6");
        }
    }//GEN-LAST:event_btnHatActionPerformed

    private void btnHetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHetActionPerformed
        if (tfEredmeny.getText().equals("0")) {
            tfEredmeny.setText("7");
        } else {
            tfEredmeny.setText(tfEredmeny.getText() + "7");
        }
    }//GEN-LAST:event_btnHetActionPerformed

    private void btnKilencActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKilencActionPerformed
        if (tfEredmeny.getText().equals("0")) {
            tfEredmeny.setText("9");
        } else {
            tfEredmeny.setText(tfEredmeny.getText() + "9");
        }
    }//GEN-LAST:event_btnKilencActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed

        tfKicsi.setText("0");
        tfEredmeny.setText("0");
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnOsszeadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsszeadasActionPerformed

//        int ablak = Integer.parseInt(tfEredmeny.getText())+Integer.parseInt(tfKicsi.getText()); 
//        tfKicsi.setText(ablak+"");
//        tfEredmeny.setText("0");
        tfKicsi.setText(tfEredmeny.getText());
        tfEredmeny.setText("0");
        muvelet = "+";
    }//GEN-LAST:event_btnOsszeadasActionPerformed

    private void btnEgyenloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgyenloActionPerformed
        
        int egyik = Integer.parseInt(tfEredmeny.getText());
        int masik = Integer.parseInt(tfKicsi.getText());

        int eredmeny = 0;
        switch (muvelet) {
            case "+":
                eredmeny = egyik + masik;
                break;
            case "-":
                eredmeny = masik - egyik;
                break;
            case "*":
                eredmeny = egyik * masik;
                break;
            case "/":
                eredmeny = masik / egyik;
                break;
        }
        tfKicsi.setText("0");
        tfEredmeny.setText(eredmeny + "");
    }//GEN-LAST:event_btnEgyenloActionPerformed

    private void tfKicsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKicsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKicsiActionPerformed

    private void btnSzorzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSzorzasActionPerformed
//        if (tfKicsi.getText().equals("0")){
//            tfKicsi.setText("1");
//        }
//        int ablak = Integer.parseInt(tfEredmeny.getText())*Integer.parseInt(tfKicsi.getText()); 
//        tfKicsi.setText(ablak+"");
//        tfEredmeny.setText("0");
        tfKicsi.setText(tfEredmeny.getText());
        tfEredmeny.setText("0");
        muvelet = "*";
    }//GEN-LAST:event_btnSzorzasActionPerformed

    private void btnOsztasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsztasActionPerformed
        tfKicsi.setText(tfEredmeny.getText());
        tfEredmeny.setText("0");
        muvelet = "/";
    }//GEN-LAST:event_btnOsztasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEgy;
    private javax.swing.JButton btnEgyenlo;
    private javax.swing.JButton btnHarom;
    private javax.swing.JButton btnHat;
    private javax.swing.JButton btnHet;
    private javax.swing.JButton btnKetto;
    private javax.swing.JButton btnKilenc;
    private javax.swing.JButton btnKivonas;
    private javax.swing.JButton btnNegy;
    private javax.swing.JButton btnNulla;
    private javax.swing.JButton btnNyolc;
    private javax.swing.JButton btnOsszeadas;
    private javax.swing.JButton btnOsztas;
    private javax.swing.JButton btnOt;
    private javax.swing.JButton btnSzorzas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfEredmeny;
    private javax.swing.JTextField tfKicsi;
    // End of variables declaration//GEN-END:variables

}
